from typing import Any

from sqlalchemy.types import TypeEngine

class Vector(TypeEngine[Any]):
    def __init__(self, dim: int) -> None: ...
    def bind_processor(self, dialect: Any) -> Any: ...
    def result_processor(self, dialect: Any, coltype: Any) -> Any: ...
